### ISSUE TITLE
Export Lona/examples/material-design/*.component  to  React Native Code  error.

### ISSUE THREAD

**Issue by michaeldong** [airbnb/Lona#130]
When I use node , try export component that in  "Lona/examples/material-design".
Error accur. It's say " Cannot destructure property `children` of 'undefined' or 'null" 

➜  Lona git:(master) ✗ node compiler/react/index.js /Users/Dong/Documents/gitHubFork/Lona  output
/Users/Dong/Documents/gitHubFork/Lona/examples/material-design/components/Card.component => output/examples/material-design/components/Card.js
/Users/Dong/Documents/gitHubFork/Lona/examples/material-design/components/ListItem.component => output/examples/material-design/components/ListItem.js
(node:40256) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `children` of 'undefined' or 'null'.
    at getLayers (/Users/Dong/Documents/gitHubFork/Lona/compiler/react/utils/layer.js:5:26)
    at getAllLayers (/Users/Dong/Documents/gitHubFork/Lona/compiler/react/utils/layer.js:14:3)
    at getAllComponentLayers (/Users/Dong/Documents/gitHubFork/Lona/compiler/react/utils/layer.js:20:10)
    at readComponent (/Users/Dong/Documents/gitHubFork/Lona/compiler/react/utils/component.js:33:31)
    at convertComponent (/Users/Dong/Documents/gitHubFork/Lona/compiler/react/convert.js:487:21)
    at files.filter.forEach (/Users/Dong/Documents/gitHubFork/Lona/compiler/react/index.js:89:22)
    at Array.forEach (<anonymous>)
    at glob (/Users/Dong/Documents/gitHubFork/Lona/compiler/react/index.js:73:8)
    at f (/Users/Dong/Documents/gitHubFork/Lona/compiler/react/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/Dong/Documents/gitHubFork/Lona/compiler/react/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (/Users/Dong/Documents/gitHubFork/Lona/compiler/react/node_modules/glob/glob.js:197:8)
    at done (/Users/Dong/Documents/gitHubFork/Lona/compiler/react/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/Users/Dong/Documents/gitHubFork/Lona/compiler/react/node_modules/glob/glob.js:637:12)
    at /Users/Dong/Documents/gitHubFork/Lona/compiler/react/node_modules/glob/glob.js:626:10

**Comment by michaeldong** [comment]
This's project has demo that can generate React Native Code?

**Comment by michaeldong** [comment]
`function getAllLayers(root) {
  const layers = [];

  const getLayers = (layer) => {
    const { children } = layer;
    if (!children || children.length === 0) return;

    children.forEach((child) => {
      layers.push(child);
      getLayers(child);
    });
  };

  getLayers(root);

  return layers;
}`

It's say root don't have children?

**Comment by michaeldong** [comment]
`function getAllLayers(root) {
const layers = [];

const getLayers = (layer) => {
const { children } = layer;
if (!children || children.length === 0) return;

children.forEach((child) => {
  layers.push(child);
  getLayers(child);
});
};

getLayers(root);

return layers;
}

`

**Comment by michaeldong** [comment]
![image](https://user-images.githubusercontent.com/1925773/37827670-61368fb0-2ed3-11e8-9b99-543a0f7a9506.png)
oh, I search there are some test js!!!

Where can I find detail instruction to generate it?
I read your ReadME ,  this instruction " node index.js workpath output" doubt me. 
I can't generate your test js code. 
Hope your reply , and help!

thanks for your great Project!

**Comment by michaeldong** [comment]
Node version: v8.10.0

**Comment by michaeldong** [comment]
Anyone can help me? or update the old ReadMe @dabbott.  Hope your reply!

**Comment by dabbott** [comment]
@michaeldong yeah, the readme needs updating. Check out https://github.com/airbnb/Lona/tree/master/compiler/core

**Comment by michaeldong** [comment]
Thanks for your link. But I follow it, It's tell me  "Expected field 'rootLayer'" .  What am I missing? look forward  your lastest ReadMe can help me. Thanks again! @dabbott 
![image](https://user-images.githubusercontent.com/1925773/37944613-eb1fad5a-31ae-11e8-9307-c6cac00b1f86.png)

**Comment by michaeldong** [comment]
Oh, I might find The Reason.  https://www.npmjs.com/package/bs-json . Your project use bs-json. 
my npm ignore bs-json.   so I can't parse component's json. 
This package has been deprecated .  Hope you update your demo.
